(ai-env) pi@raspberrypi:~ $ python3 /home/pi/battery_ai/run_async.py --weights /home/pi/battery_ai/best_ncnn_model --imgsz 320 --conf 0.35 --ocr --ocr_every 2 --ocr_budget -1 --ocr_pad 0.10 --center_shrink 0.20 --ocr_lock_conf 0.50 --expected_model CR2025 --no_tess --max_vars 4 --roi_dir /home/pi/ocr_dump/roi --pre_dir /home/pi/ocr_dump/pre --dump_rate 8 --max_dump_per_frame 8 --preview
[3:01:45.827501329] [24630]  INFO Camera camera_manager.cpp:330 libcamera v0.5.2+99-bfd68f78
[3:01:45.834593092] [24633]  INFO RPI pisp.cpp:720 libpisp version v1.2.1 981977ff21f3 29-04-2025 (14:13:50)
[3:01:45.837136080] [24633]  INFO IPAProxy ipa_proxy.cpp:180 Using tuning file /usr/share/libcamera/ipa/rpi/pisp/imx296.json
[3:01:45.844438730] [24633]  INFO Camera camera_manager.cpp:220 Adding camera '/base/axi/pcie@1000120000/rp1/i2c@80000/imx296@1a' for pipeline handler rpi/pisp
[3:01:45.844512971] [24633]  INFO RPI pisp.cpp:1179 Registered camera /base/axi/pcie@1000120000/rp1/i2c@80000/imx296@1a to CFE device /dev/media2 and ISP device /dev/media0 using PiSP variant BCM2712_D0
[3:01:45.848089639] [24630]  INFO Camera camera.cpp:1215 configuring streams: (0) 1280x960-YUV420/sYCC (1) 1456x1088-BGGR_PISP_COMP1/RAW
[3:01:45.848298082] [24633]  INFO RPI pisp.cpp:1483 Sensor: /base/axi/pcie@1000120000/rp1/i2c@80000/imx296@1a - Selected sensor format: 1456x1088-SBGGR10_1X10/RAW - Selected CFE format: 1456x1088-PC1B/RAW
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Loading /home/pi/battery_ai/best_ncnn_model for NCNN inference...
✅ OCR worker started
QFontEngineFT: Failed to create FreeType font engine
QFontEngineFT: Failed to create FreeType font engine
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/battery_ai/ocr_module.py", line 150, in ocr_worker
    variants=make_variants(crop, max_vars=max_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/battery_ai/ocr_module.py", line 61, in make_variants
    outs=[cv2.cvtColor(x,cv2.COLOR_GRAY2RGB) for x in base]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/battery_ai/ocr_module.py", line 61, in <listcomp>
    outs=[cv2.cvtColor(x,cv2.COLOR_GRAY2RGB) for x in base]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^CTraceback (most recent call last):
  File "/home/pi/battery_ai/run_async.py", line 78, in main
    dets = det.track_once(frame)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/battery_ai/yolo_detector.py", line 43, in track_once
    r = self.model.track(source=infer, imgsz=self.imgsz, conf=self.conf,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/engine/model.py", line 601, in track
    return self.predict(source=source, stream=stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/engine/model.py", line 557, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 229, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 38, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 336, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 184, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/nn/autobackend.py", line 761, in forward
    y = [np.array(ex.extract(x)[1])[None] for x in sorted(self.net.output_names())]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/ai-env/lib/python3.11/site-packages/ultralytics/nn/autobackend.py", line 761, in <listcomp>
    y = [np.array(ex.extract(x)[1])[None] for x in sorted(self.net.output_names())]
                  ^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/battery_ai/run_async.py", line 229, in <module>
    main()
  File "/home/pi/battery_ai/run_async.py", line 212, in main
    det.close()
  File "/home/pi/battery_ai/yolo_detector.py", line 62, in close
    self.picam2.close()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 707, in close
    self._cm.cleanup(self.camera_idx)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 114, in cleanup
    self.thread.join()
  File "/usr/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at 0x7fff44119d00>
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.11/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.11/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 199, in _finalize_join
    thread.join()
  File "/usr/lib/python3.11/threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
Exception ignored in: <function Picamera2.__del__ at 0x7fff1e837ce0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 501, in __del__
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 707, in close
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 109, in cleanup
KeyError: 0
